# SITE CONFIGURATION
baseurl: ""
url: "0xl4ugh.github.io"

# THEME-SPECIFIC CONFIGURATION
title: 0xL4ugh                                    # site's title
description: "CTF Players "      # used by search engines
avatar: assets/img/logo.png                         # Empty for no avatar in navbar
favicon:                           # Icon displayed in the tab

# Header and footer text
header_text: Wait for the l4ughers   # Change Blog header text
header_feature_image: assets/img/logo.png 
footer_text:  Powered by 0xl4uth


# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
